import type { StaffMemberInput } from "@/lib/staff/types";

export const NANGKA_BARANGAY_ID = "nangka-consolacion";
export const NANGKA_ORG_NAME = "Brgy. Nangka · Consolacion, Cebu";

/**
 * Working roster for Brgy. Nangka (+ Consolacion LGU MDRRMO oversight).
 * Demo account emails link to officer logins where set.
 */
export const NANGKA_STAFF_SEED: StaffMemberInput[] = [
  {
    id: "captain",
    displayName: "Hon. Ricardo Villanueva",
    title: "Punong Barangay",
    rank: "captain",
    scope: "barangay",
    reportsToId: null,
    office: "Barangay Hall · Main",
    phone: "09171234001",
    email: "captain@nangka.consolacion.demo",
    accountEmail: "captain@nangka.consolacion.demo",
    status: "active",
    notes: "Overall command · DRRM policy · evacuation orders",
  },
  {
    id: "secretary",
    displayName: "Elena Ramos",
    title: "Barangay Secretary",
    rank: "secretary",
    scope: "barangay",
    reportsToId: "captain",
    office: "Barangay Hall · Records",
    phone: "09171234002",
    email: "secretary@nangka.consolacion.demo",
    status: "active",
    notes: "Minutes · sitreps · document control",
  },
  {
    id: "treasurer",
    displayName: "Benjamin Ong",
    title: "Barangay Treasurer",
    rank: "treasurer",
    scope: "barangay",
    reportsToId: "captain",
    office: "Barangay Hall · Finance",
    phone: "09171234003",
    email: "treasurer@nangka.consolacion.demo",
    status: "active",
    notes: "Relief funds · logistics procurement",
  },
  {
    id: "kagawad-peace",
    displayName: "Antonio Dela Peña",
    title: "Kagawad · Peace & Order",
    rank: "kagawad",
    scope: "barangay",
    reportsToId: "captain",
    office: "Barangay Hall",
    phone: "09171234004",
    email: "kagawad.peace@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "kagawad-health",
    displayName: "Sofia Marquez",
    title: "Kagawad · Health",
    rank: "kagawad",
    scope: "barangay",
    reportsToId: "captain",
    office: "Barangay Health Station",
    phone: "09171234005",
    email: "kagawad.health@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "kagawad-infra",
    displayName: "Paolo Gutierrez",
    title: "Kagawad · Infrastructure",
    rank: "kagawad",
    scope: "barangay",
    reportsToId: "captain",
    office: "Barangay Hall",
    phone: "09171234006",
    email: "kagawad.infra@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "sk",
    displayName: "Mia Fernandez",
    title: "SK Chairperson",
    rank: "sk_chair",
    scope: "barangay",
    reportsToId: "captain",
    office: "SK Office",
    phone: "09171234007",
    email: "sk@nangka.consolacion.demo",
    status: "active",
    notes: "Youth volunteers · evacuation center support",
  },
  {
    id: "mdrrmo",
    displayName: "Maria Santos",
    title: "BDRRMC Coordinator · MDRRMO Focal",
    rank: "mdrrmo",
    scope: "barangay",
    reportsToId: "captain",
    office: "MDRRMO Desk · Barangay Hall",
    phone: "09171234008",
    email: "officer@nangka.consolacion.demo",
    accountEmail: "officer@nangka.consolacion.demo",
    status: "active",
    notes: "Ops map · triage · SMS/email alerts · Odette simulation lead",
  },
  {
    id: "rescue-lead",
    displayName: "Joel Cabrera",
    title: "Rescue Team Lead",
    rank: "staff",
    scope: "barangay",
    reportsToId: "mdrrmo",
    office: "MDRRMO Desk",
    phone: "09171234009",
    email: "rescue@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "ew-radio",
    displayName: "Gina Morales",
    title: "Early Warning / Radio Net",
    rank: "staff",
    scope: "barangay",
    reportsToId: "mdrrmo",
    office: "MDRRMO Desk",
    phone: "09171234010",
    email: "radio@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "tanod-chief",
    displayName: "Ramon Sy",
    title: "Chief Tanod",
    rank: "tanod_chief",
    scope: "barangay",
    reportsToId: "kagawad-peace",
    office: "Tanod Outpost",
    phone: "09171234011",
    email: "tanod.chief@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "tanod-1",
    displayName: "Mark Villar",
    title: "Barangay Tanod · Purok 1–3",
    rank: "tanod",
    scope: "barangay",
    reportsToId: "tanod-chief",
    office: "Tanod Outpost",
    phone: "09171234012",
    email: "tanod1@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "tanod-2",
    displayName: "Eric Lim",
    title: "Barangay Tanod · Purok 4–6",
    rank: "tanod",
    scope: "barangay",
    reportsToId: "tanod-chief",
    office: "Tanod Outpost",
    phone: "09171234013",
    email: "tanod2@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "bhw-1",
    displayName: "Rosa Castillo",
    title: "Barangay Health Worker",
    rank: "bhw",
    scope: "barangay",
    reportsToId: "kagawad-health",
    office: "Barangay Health Station",
    phone: "09171234014",
    email: "bhw@nangka.consolacion.demo",
    status: "active",
  },
  {
    id: "lgu-mdrrmo",
    displayName: "Atty. Carla Mendoza",
    title: "Consolacion MDRRMO · Municipal Officer",
    rank: "lgu_director",
    scope: "lgu",
    reportsToId: null,
    office: "Consolacion Municipal Hall · MDRRMO",
    phone: "09171234901",
    email: "lgu@consolacion.demo",
    accountEmail: "lgu@consolacion.demo",
    status: "active",
    notes: "LGU oversight · resource request · inter-barangay coordination",
  },
  {
    id: "lgu-ops",
    displayName: "Diego Navarro",
    title: "Consolacion MDRRMO · Ops Staff",
    rank: "staff",
    scope: "lgu",
    reportsToId: "lgu-mdrrmo",
    office: "Consolacion Municipal Hall · MDRRMO",
    phone: "09171234902",
    email: "lgu.ops@consolacion.demo",
    status: "active",
  },
];
